{% set name = "pymeshfix" %}
{% set version = "0.16.0" %}

package:
  name: pymeshfix
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e50c499c3baa072bc7bdfbd3ea2dfbcd799b2c6217894e6948c69c82d836d46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
    - python
  host:
    - cython
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymeshfix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyvista/pymeshfix
  summary: Python Wrapper for MeshFix to easily repair holes in surface meshes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
    - larsoner
